listening-port=3478
tls-listening-port=5349
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=change-me-turn-secret
realm=16launcher.local
no-cli
no-tlsv1
no-tlsv1_1
log-file=stdout
verbose
